language: python
python:
  # Run on both Pyuthon 2.7 and 3.5
  - "2.7"
  - "3.5"

# Install the module and the dependencies
install:
  - pip install .

# Run the tests
script: 
  - python setup.py test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./checkdocs.sh; fi'
