language: python
python:
  - "2.7"
  - "3.5"

# Install the module and the dependencies
install:
  - pip2 install .
  - pip3 install .

# Run the tests with both Python 2 and 3
script: 
  - python2 setup.py test
  - python3 setup.py test
